# Site settings
title:       Oliver Joseph di Leonardo Paisley
email:       oliver@ojdp19.com
author:      "Oliver Paisley"
description: "A person website for Oliver"
baseurl:     ""
url:         "http://ojdp19.com"

# Optional features
show_related_posts: false
show_post_footers:  true

# Disqus post comments
disqus_shortname: "ojdp19"

# Social icons
github_username: oliverpaisley
stackoverflow_id:
twitter_username: oliverjdpaisley


# Build settings
highlighter: pygments
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true

exclude:
    - _sass

plugins: [jekyll-paginate]
