# Site settings
title:       Observable Data
email:       oliver@observabledata.com
author:      "Oliver Paisley"
description: "A blog about R, data science, and cool visualizations."
baseurl:     ""
url:         "http://observabledata.com"

# Google analytics
google_analytics: "UA-65908947-1"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "observabledata"

# Social icons
github_username: oliverpaisley
stackoverflow_id:
twitter_username: oliverjdpaisley
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post&#58;'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
highlighter: pygments
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-sitemap
